### ISSUE TITLE
FR6. Product Catalog/Store UI navigation

### ISSUE THREAD

**Issue by Kasataya** [WSU-4110/AR-Interior-Design#8]
|FR6. Product Catalog/Store UI navigation|
|---|
|**Goal**: Ensure a variety of different products are displayed in the application
**Stakeholders:** Customers|
| **Description:** Have a display section where users can go through a bunch of stores in the application with ease. |
| **Origin:** Based on the initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0 |
|**Date:** 02/04/2024
| **Priority:** 8 |

**Comment by Bryan-Lor** [comment]
Rory has been assigned and started working on this during two weeks of development, he just forgot to also assign himself here on Github

**Comment by roryslange** [comment]
Been working on issue since beginning of project 

- [x] Create cards, determine size to fit on most devices and contain image, brand, name price
- [x] dynamically resize cards based on screen size
- [x] make sure large number of cards can be displayed without much lag
- [x] style cards
- [x] touchable
- [x] integrate with backend

**Comment by roryslange** [comment]
waiting on backend integration then cards will be able to pull information from firebase. As of right now issue is done and cards have been designed.

**Comment by roryslange** [comment]
integration with backend was completed, issue is now fully complete.
